---
# Configure external etcd cluster nodes

- name: Install etcd package
  apt:
    name: etcd
    state: present
  failed_when: false
  register: etcd_install_result

- name: Install etcd manually if package unavailable
  block:
    - name: Download etcd binaries
      get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
        dest: "/tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
        mode: 0644

    - name: Extract etcd archive
      unarchive:
        src: "/tmp/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
        dest: /tmp
        remote_src: yes

    - name: Move etcd binaries to system path
      copy:
        src: "/tmp/etcd-{{ etcd_version }}-linux-amd64/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
        remote_src: yes
      loop:
        - etcd
        - etcdctl
        - etcdutl

    - name: Create etcd data directory
      file:
        path: "{{ etcd_data_dir }}"
        state: directory
        mode: 0755

    - name: Create etcd configuration directory
      file:
        path: /etc/etcd
        state: directory
        mode: 0755

    - name: Create etcd service file
      copy:
        dest: /etc/systemd/system/etcd.service
        content: |
          [Unit]
          Description=etcd key-value store
          Documentation=https://github.com/etcd-io/etcd
          After=network.target

          [Service]
          User=etcd
          Type=notify
          EnvironmentFile=/etc/default/etcd
          ExecStart=/usr/local/bin/etcd
          Restart=always
          RestartSec=10s
          LimitNOFILE=40000

          [Install]
          WantedBy=multi-user.target
        mode: 0644

    - name: Create etcd user
      user:
        name: etcd
        system: yes
        shell: /bin/false
        home: "{{ etcd_data_dir }}"

    - name: Set ownership of etcd data directory
      file:
        path: "{{ etcd_data_dir }}"
        owner: etcd
        group: etcd
        state: directory
        recurse: yes
  when: etcd_install_result is failed

- name: Configure etcd server
  template:
    src: etcd.defaults.j2
    dest: /etc/default/etcd
    mode: 0644
  notify: restart etcd

- name: Ensure etcd is started and enabled
  service:
    name: etcd
    state: started
    enabled: yes

- name: Wait for etcd cluster to be ready
  shell: "ETCDCTL_API=3 etcdctl member list --endpoints=http://{{ item.ip }}:2379"
  register: etcd_status
  until: etcd_status.rc == 0
  retries: 6
  delay: 10
  with_items: "{{ etcd_nodes }}"
  changed_when: false
  when: inventory_hostname == groups['etcd'][0]
